baseURL = 'https://kyleburnsdev.github.io/maker-learn-and-share/'
languageCode = 'en-us'
title = 'Toolpath Studio'
theme = 'toolpathstudio'

# Content directory
contentDir = 'content'

# Build configuration
[build]
  writeStats = true

# Pagination
paginate = 10
paginatePath = 'page'

# Permalinks
[permalinks]
  blog = '/blog/:year/:month/:slug/'

# Taxonomies (categories and tags)
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Author information
[params]
  author = 'Kyle Burns'
  description = 'Toolpath Studio is your go-to space for learning and leveling up in the world of digital fabrication. From CNC milling and 3D printing to laser engraving and vinyl cutting, we explore the tools, techniques, and workflows that bring ideas to life. Whether you’re just starting your maker journey or looking to share your own tips, this community is all about building, experimenting, and growing together - one toolpath at a time.'
  
  # Social links
  [params.social]
    youtube = 'https://www.youtube.com/channel/UCqzxSXgRG4fFjV2s3x65dPQ'  # Add your YouTube channel URL
    facebook = ''  # Add your Facebook URL
    discord = ''   # Add your Discord invite URL
    github = 'https://github.com/kyleburnsdev'

# Menu configuration
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 2

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 3

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML in markdown
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = true

# Output formats
[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']

# RSS configuration
[outputFormats.RSS]
  mediaType = 'application/rss+xml'
  baseName = 'feed'
